# Use Apache Airflow with Python 3.8
FROM apache/airflow:2.5.1-python3.8  

# Install dbt-core and dbt-bigquery adapter
RUN pip install dbt-core==1.8.7 dbt-bigquery==1.8.2 
#dbt-common needed?

# Ensure compatible versions for Airflow and its dependencies
RUN pip install 'jinja2>=3.1.3,<4' 'google-cloud-storage<2.0'

# Install python-dotenv
RUN pip install python-dotenv

# Install protobuf 3.20.x
RUN pip install protobuf==3.20.*