version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    container_name: postgres-db

  airflow-webserver:
    build: .  
    command: webserver  
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=${DOCKER_GOOGLE_APPLICATION_CREDENTIALS}  
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    volumes:
      - ../src/dags:/opt/airflow/dags
      - ../src/transform:/opt/airflow/src/transform
      - ../src/ingest:/opt/airflow/src/ingest
      - ../config/dbt:/opt/airflow/config/dbt
      - ../src/dags/logs:/opt/airflow/logs
      - ${LOCAL_GOOGLE_APPLICATION_CREDENTIALS}:/opt/airflow/gcp_credentials.json
    container_name: airflow-webserver
    env_file:
      - .env
      
  airflow-scheduler:
    build: .
    command: scheduler  
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=${DOCKER_GOOGLE_APPLICATION_CREDENTIALS}  
    depends_on:
      - airflow-init
    volumes:
      - ../src/dags:/opt/airflow/dags
      - ../src/transform:/opt/airflow/src/transform
      - ../src/ingest:/opt/airflow/src/ingest
      - ../config/dbt:/opt/airflow/config/dbt
      - ../src/dags/logs:/opt/airflow/logs
      - ${LOCAL_GOOGLE_APPLICATION_CREDENTIALS}:/opt/airflow/gcp_credentials.json  
    container_name: airflow-scheduler
    env_file: 
      - .env

  airflow-init:
    build: .
    command: bash -c "airflow db init"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres
    container_name: airflow-init

volumes:
  postgres-db-volume:
