# Naming the project
name: 'football_data_pipeline'
version: '1.0.0'

# Specifying the profile
profile: 'football_data_pipeline'

# Configuring paths for different dbt artifacts
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"
  
# Model configurations for different layers
models:
  football_data_pipeline:
    
    staging:
      +schema: "staging"  # Transform layer
      +materialized: table  
      
    marts:
      +schema: "marts"  # Aggregate & analytics layer
      +materialized: view  

snapshots:
  football_data_pipeline:
    +schema: "snapshot"  # The schema where snapshot tables will be stored
    +database: "{{ env_var('GCP_PROJECT_ID', 'default_project') }}"  # The BigQuery project ID
    +invalidate_hard_deletes: true
