# Naming the project
name: 'football_data_pipeline'
version: 2

# Specifying the profile
profile: 'football_data_pipeline'

# Configuring paths for different dbt artifacts
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"
  
# Defining variables for BigQuery configurations, using environment variables for flexibility
vars:
  bigquery_dataset: "{{ env_var('BIGQUERY_DATASET', 'default_dataset') }}"  
  gcp_project_id: "{{ env_var('GCP_PROJECT_ID', 'default_project') }}"  

# Model configurations for different layers
models:
  football_data_pipeline:
    
    silver:
      +schema: "silver"  # Transform layer
      +materialized: table  
      
    gold:
      +schema: "gold"  # Aggregate & analytics layer
      +materialized: table  

snapshots:
  football_data_pipeline:
    +schema: "snapshot"  # The schema where snapshot tables will be stored
    +database: "{{ env_var('GCP_PROJECT_ID', 'default_project') }}"  # The BigQuery project ID
    +invalidate_hard_deletes: true
