name: CI/CD Pipeline for dbt

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-bigquery

    - name: Set environment variable for Google Cloud Credentials
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.DOCKER_GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS_JSON" > /tmp/gcp_credentials.json  
        ls -la /tmp/gcp_credentials.json  
        cat /tmp/gcp_credentials.json  #

    # Use the JSON file for credentials
    - name: Set up Google Cloud Credentials
      run: |
        export DOCKER_GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_credentials.json"
        echo $DOCKER_GOOGLE_APPLICATIONS_CREDENTIALS

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        cp config/dbt/profiles.yml ~/.dbt/profiles.yml  # Copy profiles.yml to the default dbt location

    - name: Run dbt models
      env:
        GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}  # Use GitHub repository variable
        BIGQUERY_DATASET: ${{ vars.BIGQUERY_DATASET }}  # Use GitHub repository variable
        DOCKER_GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json  # Explicitly pass the environment variable
      run: |
        dbt deps  # Install dbt packages
        dbt run
      working-directory: ./src/transform  

    - name: Run dbt tests
      run: |
        dbt test
      working-directory: ./src/transform  