name: CI/CD Pipeline for dbt

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-bigquery

    # Write the Google Cloud credentials from the secret to a JSON file
    - name: Create Google Cloud Credentials JSON
      run: |
        echo "${{ secrets.DOCKER_GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/gcp_credentials.json
        ls -la /tmp/gcp_credentials.json  # Verify the file has been created
        cat /tmp/gcp_credentials.json  # Output the content to verify it's not empty (for debugging purposes)

    # Check if the environment variable is set correctly
    - name: Check Environment Variable
      run: |
        export DOCKER_GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_credentials.json"
        echo $DOCKER_GOOGLE_APPLICATION_CREDENTIALS  # Verify the variable is set

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        cp config/dbt/profiles.yml ~/.dbt/profiles.yml  # Copy profiles.yml to the default dbt location

    - name: Run dbt models
      env:
        GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}  # Use GitHub repository variable
        BIGQUERY_DATASET: ${{ vars.BIGQUERY_DATASET }}  # Use GitHub repository variable
        DOCKER_GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json  # Explicitly pass the environment variable
      run: |
        dbt deps  # Install dbt packages
        dbt run
      working-directory: ./src/transform  

    - name: Run dbt tests
      run: |
        dbt test
      working-directory: ./src/transform  